
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 08 20:42:44 CST 2025
//----------------------------------------------------

package Parser;

import java.util.*;
import java_cup.runtime.*;
import Clases.*;
import Errores.ErrorSintactico;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Sep 08 20:42:44 CST 2025
  */
public class AnalizadorSintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public AnalizadorSintactico() {super();}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalizadorSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\047\000\002\002\004\000\002\002\003\000\002\003" +
    "\002\000\002\003\004\000\002\004\003\000\002\004\003" +
    "\000\002\005\003\000\002\005\003\000\002\006\046\000" +
    "\002\007\054\000\002\010\003\000\002\010\005\000\002" +
    "\013\003\000\002\013\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\005\000\002\011\005\000\002\012\003" +
    "\000\002\012\005\000\002\030\003\000\002\030\003\000" +
    "\002\030\003\000\002\014\003\000\002\015\003\000\002" +
    "\015\005\000\002\017\003\000\002\017\004\000\002\021" +
    "\006\000\002\023\003\000\002\023\005\000\002\025\005" +
    "\000\002\025\005\000\002\020\003\000\002\020\004\000" +
    "\002\022\021\000\002\027\006\000\002\027\007\000\002" +
    "\027\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\014\002\uffff\004\uffff\013\uffff\014\uffff\027" +
    "\uffff\001\002\000\004\002\232\001\002\000\014\002\000" +
    "\004\010\013\016\014\014\027\015\001\002\000\014\002" +
    "\ufffd\004\ufffd\013\ufffd\014\ufffd\027\ufffd\001\002\000\014" +
    "\002\ufffe\004\ufffe\013\ufffe\014\ufffe\027\ufffe\001\002\000" +
    "\006\007\033\010\032\001\002\000\014\002\ufffb\004\ufffb" +
    "\013\ufffb\014\ufffb\027\ufffb\001\002\000\014\002\ufffc\004" +
    "\ufffc\013\ufffc\014\ufffc\027\ufffc\001\002\000\014\002\ufffa" +
    "\004\ufffa\013\ufffa\014\ufffa\027\ufffa\001\002\000\004\027" +
    "\026\001\002\000\004\020\022\001\002\000\004\020\017" +
    "\001\002\000\004\021\020\001\002\000\004\023\021\001" +
    "\002\000\014\002\uffdd\004\uffdd\013\uffdd\014\uffdd\027\uffdd" +
    "\001\002\000\004\031\023\001\002\000\004\021\024\001" +
    "\002\000\004\023\025\001\002\000\014\002\uffdb\004\uffdb" +
    "\013\uffdb\014\uffdb\027\uffdb\001\002\000\004\020\027\001" +
    "\002\000\004\021\030\001\002\000\004\023\031\001\002" +
    "\000\014\002\uffdc\004\uffdc\013\uffdc\014\uffdc\027\uffdc\001" +
    "\002\000\004\011\133\001\002\000\004\011\034\001\002" +
    "\000\004\015\035\001\002\000\004\031\036\001\002\000" +
    "\004\005\037\001\002\000\004\027\040\001\002\000\004" +
    "\015\041\001\002\000\004\016\042\001\002\000\006\027" +
    "\043\030\044\001\002\000\020\017\ufff5\020\ufff5\022\ufff5" +
    "\023\ufff5\024\ufff5\025\ufff5\026\ufff5\001\002\000\020\017" +
    "\ufff4\020\ufff4\022\ufff4\023\ufff4\024\ufff4\025\ufff4\026\ufff4" +
    "\001\002\000\006\017\ufff7\022\ufff7\001\002\000\006\017" +
    "\050\022\047\001\002\000\006\027\043\030\044\001\002" +
    "\000\004\023\051\001\002\000\004\027\052\001\002\000" +
    "\004\015\053\001\002\000\004\016\054\001\002\000\006" +
    "\027\055\030\056\001\002\000\006\017\ufff3\022\ufff3\001" +
    "\002\000\006\017\ufff2\022\ufff2\001\002\000\006\017\061" +
    "\022\060\001\002\000\006\027\130\030\131\001\002\000" +
    "\004\023\062\001\002\000\004\027\063\001\002\000\004" +
    "\015\064\001\002\000\004\016\065\001\002\000\006\027" +
    "\043\030\044\001\002\000\004\017\070\001\002\000\004" +
    "\017\uffea\001\002\000\004\023\071\001\002\000\004\027" +
    "\072\001\002\000\004\015\073\001\002\000\004\016\074" +
    "\001\002\000\006\027\043\030\044\001\002\000\006\017" +
    "\100\022\077\001\002\000\006\017\uffe9\022\uffe9\001\002" +
    "\000\006\027\043\030\044\001\002\000\004\023\101\001" +
    "\002\000\004\012\102\001\002\000\004\024\103\001\002" +
    "\000\006\027\043\030\044\001\002\000\010\006\uffe7\027" +
    "\uffe7\030\uffe7\001\002\000\010\006\124\027\043\030\044" +
    "\001\002\000\004\025\107\001\002\000\006\027\110\030" +
    "\111\001\002\000\004\022\121\001\002\000\004\022\117" +
    "\001\002\000\006\023\uffe4\026\uffe4\001\002\000\006\023" +
    "\114\026\115\001\002\000\010\006\uffe5\027\uffe5\030\uffe5" +
    "\001\002\000\006\027\110\030\111\001\002\000\006\023" +
    "\uffe3\026\uffe3\001\002\000\006\027\043\030\044\001\002" +
    "\000\006\023\uffe1\026\uffe1\001\002\000\006\027\043\030" +
    "\044\001\002\000\006\023\uffe2\026\uffe2\001\002\000\010" +
    "\006\uffe6\027\uffe6\030\uffe6\001\002\000\004\007\125\001" +
    "\002\000\004\005\126\001\002\000\014\002\ufff9\004\ufff9" +
    "\013\ufff9\014\ufff9\027\ufff9\001\002\000\006\017\uffe8\022" +
    "\uffe8\001\002\000\006\017\ufff1\022\ufff1\001\002\000\006" +
    "\017\ufff0\022\ufff0\001\002\000\006\017\ufff6\022\ufff6\001" +
    "\002\000\004\015\134\001\002\000\004\031\135\001\002" +
    "\000\004\005\136\001\002\000\004\027\137\001\002\000" +
    "\004\015\140\001\002\000\004\016\141\001\002\000\006" +
    "\027\043\030\044\001\002\000\006\017\143\022\047\001" +
    "\002\000\004\023\144\001\002\000\004\027\145\001\002" +
    "\000\004\015\146\001\002\000\004\016\147\001\002\000" +
    "\006\027\055\030\056\001\002\000\006\017\151\022\060" +
    "\001\002\000\004\023\152\001\002\000\004\027\153\001" +
    "\002\000\004\015\154\001\002\000\004\016\155\001\002" +
    "\000\010\027\156\032\157\033\160\001\002\000\010\017" +
    "\uffed\021\uffed\022\uffed\001\002\000\010\017\uffec\021\uffec" +
    "\022\uffec\001\002\000\010\017\uffeb\021\uffeb\022\uffeb\001" +
    "\002\000\006\017\uffef\022\uffef\001\002\000\006\017\164" +
    "\022\163\001\002\000\010\027\156\032\157\033\160\001" +
    "\002\000\004\023\165\001\002\000\004\027\166\001\002" +
    "\000\004\015\167\001\002\000\004\016\170\001\002\000" +
    "\006\027\043\030\044\001\002\000\004\017\172\001\002" +
    "\000\004\023\173\001\002\000\004\027\174\001\002\000" +
    "\004\015\175\001\002\000\004\016\176\001\002\000\006" +
    "\027\043\030\044\001\002\000\006\017\200\022\077\001" +
    "\002\000\004\023\201\001\002\000\004\012\202\001\002" +
    "\000\004\024\203\001\002\000\006\027\043\030\044\001" +
    "\002\000\010\006\uffe0\027\uffe0\030\uffe0\001\002\000\010" +
    "\006\225\027\043\030\044\001\002\000\004\020\207\001" +
    "\002\000\010\027\156\032\157\033\160\001\002\000\004" +
    "\021\211\001\002\000\004\025\212\001\002\000\004\020" +
    "\213\001\002\000\010\027\156\032\157\033\160\001\002" +
    "\000\004\021\215\001\002\000\004\022\216\001\002\000" +
    "\006\027\043\030\044\001\002\000\004\024\220\001\002" +
    "\000\004\020\221\001\002\000\010\027\156\032\157\033" +
    "\160\001\002\000\004\021\223\001\002\000\004\023\224" +
    "\001\002\000\010\006\uffde\027\uffde\030\uffde\001\002\000" +
    "\004\010\227\001\002\000\010\006\uffdf\027\uffdf\030\uffdf" +
    "\001\002\000\004\005\230\001\002\000\014\002\ufff8\004" +
    "\ufff8\013\ufff8\014\ufff8\027\ufff8\001\002\000\006\017\uffee" +
    "\022\uffee\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\230\000\006\002\003\003\004\001\001\000\002\001" +
    "\001\000\014\004\006\005\005\006\010\007\012\027\011" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\010" +
    "\045\013\044\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\131\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\056\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\013\066\014\065\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\013\075" +
    "\015\074\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\013\126\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\013\105\017\104\021\103\001" +
    "\001\000\002\001\001\000\006\013\105\021\122\001\001" +
    "\000\002\001\001\000\006\023\112\025\111\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\025\115\001\001\000" +
    "\002\001\001\000\004\013\117\001\001\000\002\001\001" +
    "\000\004\013\121\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\010\141\013\044\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\011\147\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\012\161\030\160\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\030\230\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\013\066\014\170\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\013\075\015\176\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\013\205\020\204\022\203\001\001\000\002" +
    "\001\001\000\006\013\205\022\225\001\001\000\002\001" +
    "\001\000\004\030\207\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\213\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\013\216\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\030\221\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalizadorSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalizadorSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalizadorSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Lista global de errores sintácticos
    public static ArrayList<ErrorSintactico> erroresSintacticos = new ArrayList<>();

    // (Opcional) variables capturadas por el lexer — las dejamos por compatibilidad
    private String nombreCapturado;
    private String cadenaCapturada;

    public void capturarNombre(String nombre) { this.nombreCapturado = nombre; }
    public void capturarCadena(String cadena) { this.cadenaCapturada = cadena; }
    public String getNombreCapturado() { return nombreCapturado; }
    public String getCadenaCapturada() { return cadenaCapturada; }

    @Override
    public void syntax_error(Symbol cur_token) {
        erroresSintacticos.add(new ErrorSintactico(
            cur_token.left+1,
            cur_token.right+1,
            (cur_token.value != null) ? cur_token.value.toString() : "null",
            "Sintáctico"
        ));
    }

    @Override
    public void unrecovered_syntax_error(Symbol cur_token) {
        erroresSintacticos.add(new ErrorSintactico(
            cur_token.left+1,
            cur_token.right+1,
            (cur_token.value != null) ? cur_token.value.toString() : "null",
            "Irrecuperable"
        ));
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$AnalizadorSintactico$actions {
  private final AnalizadorSintactico parser;

  /** Constructor */
  CUP$AnalizadorSintactico$actions(AnalizadorSintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$AnalizadorSintactico$do_action(
    int                        CUP$AnalizadorSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalizadorSintactico$parser,
    java.util.Stack            CUP$AnalizadorSintactico$stack,
    int                        CUP$AnalizadorSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalizadorSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalizadorSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // comando ::= ID PAREN_IZQ CADENA PAREN_DER PUNTO_COMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)).value;
		int cadleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int cadright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String cad = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		 
        System.out.println("[COMANDO] VALIDACION ejecutado sobre: " + nombre + " con cadena: " + cad);
        FuncionesAutomata.validarCadena(nombre, cad);
        RESULT = null;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comando",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // comando ::= DESC ID PAREN_IZQ PAREN_DER PUNTO_COMA 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		 
        System.out.println("[COMANDO] DESC ejecutado sobre: " + nombre);
        FuncionesAutomata.descripcionAutomata(nombre);
        RESULT = null;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comando",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // comando ::= VER_AUTOMATAS PAREN_IZQ PAREN_DER PUNTO_COMA 
            {
              Object RESULT =null;
		 
        System.out.println("[COMANDO] VER_AUTOMATAS ejecutado");
        FuncionesAutomata.verAutomatas();
        RESULT = null;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("comando",21, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // transicion_ap ::= estado PAREN_IZQ simbolo PAREN_DER FLECHA PAREN_IZQ simbolo PAREN_DER COMA estado DOS_PUNTOS PAREN_IZQ simbolo PAREN_DER PUNTO_COMA 
            {
              List RESULT =null;
		int origenleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).left;
		int origenright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).right;
		String origen = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).value;
		int symInleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-12)).left;
		int symInright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-12)).right;
		String symIn = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-12)).value;
		int symPopleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).left;
		int symPopright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).right;
		String symPop = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).value;
		int destleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).left;
		int destright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).right;
		String dest = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-5)).value;
		int symPushleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int symPushright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String symPush = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		 
        System.out.println("Procesando transición AP completa - Origen: " + origen + ", Entrada: " + symIn + ", Extrae: " + symPop + ", Destino: " + dest + ", Inserta: " + symPush);
        
        Map<String, String> transicionCompleta = new HashMap<>();
        transicionCompleta.put("origen", (String)origen);
        transicionCompleta.put("simboloEntrada", symIn);
        transicionCompleta.put("simboloExtrae", symPop);
        transicionCompleta.put("destino", (String)dest);
        transicionCompleta.put("simboloInserta", symPush);
        
        List<Map<String, String>> transicionesCompletas = new ArrayList<>();
        transicionesCompletas.add(transicionCompleta);
        
        RESULT = transicionesCompletas;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transicion_ap",16, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // transiciones_ap ::= transiciones_ap transicion_ap 
            {
              List RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		List list = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		List t = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List)list).addAll((List)t);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transiciones_ap",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // transiciones_ap ::= transicion_ap 
            {
              List RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		List t = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        RESULT = t;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transiciones_ap",14, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // opcion_afd ::= NUMERO COMA estado 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int destleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int destright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String dest = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        Map<String, String> transMap = new HashMap<>();
        transMap.put("simbolo", s);
        transMap.put("destino", (String)dest);
        RESULT = transMap;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("opcion_afd",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // opcion_afd ::= ID COMA estado 
            {
              Object RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int destleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int destright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String dest = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        Map<String, String> transMap = new HashMap<>();
        transMap.put("simbolo", s);
        transMap.put("destino", (String)dest);
        RESULT = transMap;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("opcion_afd",19, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // opciones_afd ::= opciones_afd OR opcion_afd 
            {
              List RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List list = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int oleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List)list).add(o);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("opciones_afd",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // opciones_afd ::= opcion_afd 
            {
              List RESULT =null;
		int oleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int oright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		Object o = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List l = new ArrayList();
        l.add(o);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("opciones_afd",17, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // transicion_afd ::= estado FLECHA opciones_afd PUNTO_COMA 
            {
              List RESULT =null;
		int origenleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int origenright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		String origen = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		int opsleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int opsright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		List ops = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		 
        List<Map<String, String>> transicionesCompletas = new ArrayList<>();
        
        if (ops instanceof List) {
            for (Object opcion : (List)ops) {
                if (opcion instanceof Map) {
                    Map<String, String> opcionMap = (Map<String, String>)opcion;
                    Map<String, String> transicionCompleta = new HashMap<>();
                    transicionCompleta.put("origen", (String)origen);
                    transicionCompleta.put("simbolo", opcionMap.get("simbolo"));
                    transicionCompleta.put("destino", opcionMap.get("destino"));
                    transicionesCompletas.add(transicionCompleta);
                }
            }
        }
        RESULT = transicionesCompletas;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transicion_afd",15, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // transiciones_afd ::= transiciones_afd transicion_afd 
            {
              List RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		List list = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		List t = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List)list).addAll((List)t);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transiciones_afd",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // transiciones_afd ::= transicion_afd 
            {
              List RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		List t = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        RESULT = t;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("transiciones_afd",13, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // estados_aceptacion ::= estados_aceptacion COMA estado 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List<String>)list).add((String)e);
        System.out.println("Estado de aceptación: ..." + e);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estados_aceptacion",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // estados_aceptacion ::= estado 
            {
              List<String> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List<String> l = new ArrayList<String>();
        l.add((String)e);
        System.out.println("Estado de aceptación: " + e);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estados_aceptacion",11, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // estado_inicial ::= estado 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        System.out.println("Estado inicial: " + e);
        RESULT = e;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estado_inicial",10, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // simbolo ::= STACKTOP 
            {
              String RESULT =null;
		int stackleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int stackright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String stack = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = stack; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("simbolo",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // simbolo ::= LAMBDA 
            {
              String RESULT =null;
		int lambdaleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int lambdaright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String lambda = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = lambda; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("simbolo",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // simbolo ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = id; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("simbolo",22, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // alfabeto_pila ::= alfabeto_pila COMA simbolo 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List<String>)list).add(e);
        System.out.println("Símbolo pila agregado: ..." + e);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto_pila",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // alfabeto_pila ::= simbolo 
            {
              List<String> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List<String> l = new ArrayList<String>();
        l.add(e);
        System.out.println("Símbolo pila agregado: " + e);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto_pila",8, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // alfabeto ::= alfabeto COMA NUMERO 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List<String>)list).add(e);
        System.out.println("Alfabeto agregado: ..." + e);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // alfabeto ::= alfabeto COMA ID 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List<String>)list).add(e);
        System.out.println("Alfabeto agregado: ..." + e);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // alfabeto ::= NUMERO 
            {
              List<String> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List<String> l = new ArrayList<String>();
        l.add(e);
        System.out.println("Alfabeto agregado: " + e);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // alfabeto ::= ID 
            {
              List<String> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List<String> l = new ArrayList<String>();
        l.add(e);
        System.out.println("Alfabeto agregado: " + e);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("alfabeto",7, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // estado ::= NUMERO 
            {
              String RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String num = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = num; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estado",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // estado ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 RESULT = id; 
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estado",9, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // estados ::= estados COMA estado 
            {
              List<String> RESULT =null;
		int listleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).left;
		int listright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).right;
		List<String> list = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        ((List<String>)list).add((String)e);
        System.out.println("Estado agregado: ..." + e);
        RESULT = list;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estados",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // estados ::= estado 
            {
              List<String> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.peek()).value;
		 
        List<String> l = new ArrayList<String>();
        l.add((String)e);
        System.out.println("Estado agregado: " + e);
        RESULT = l;
      
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("estados",6, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ap ::= MENOR AP NOMBRE IGUAL CADENA MAYOR ID IGUAL LLAVE_IZQ estados LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ alfabeto LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ alfabeto_pila LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ estado_inicial LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ estados_aceptacion LLAVE_DER PUNTO_COMA TRANSICIONES DOS_PUNTOS transiciones_ap MENOR_DIAGONAL AP MAYOR 
            {
              Object RESULT =null;
		int nombreCadenaleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-37)).left;
		int nombreCadenaright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-37)).right;
		String nombreCadena = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-37)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-32)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-32)).right;
		List<String> est = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-32)).value;
		int alfleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).left;
		int alfright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).right;
		List<String> alf = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).value;
		int alfpleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).left;
		int alfpright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).right;
		List<String> alfp = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).value;
		int eileft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).left;
		int eiright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).right;
		String ei = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).value;
		int eaccleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).left;
		int eaccright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).right;
		List<String> eacc = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).value;
		int trsleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int trsright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		List trs = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		 
        String nombreAutomata = (String)nombreCadena;
        System.out.println("=== INICIANDO PROCESAMIENTO AP ===");
        System.out.println("Nombre del AP: " + nombreAutomata);

        List<Estado> listaEstados = new ArrayList<Estado>();
        for (String n : (List<String>)est) {
            Estado e = new Estado(n);
            if (n != null && n.equals(ei)) e.setInicial(true);
            if (eacc != null && ((List<String>)eacc).contains(n)) e.setAceptacion(true);
            listaEstados.add(e);
        }

        System.out.println("=== Estados AP ===");
        for (Estado ee : listaEstados) {
            System.out.println("  " + ee);
        }

        System.out.println("=== Alfabeto entrada AP ===");
        if (alf != null) {
            for (String s : (List<String>)alf) System.out.println("  " + s);
        }

        System.out.println("=== Alfabeto pila AP ===");
        if (alfp != null) {
            for (String s : (List<String>)alfp) System.out.println("  " + s);
        }

        // Método auxiliar para buscar estados por nombre (para AP)
        java.util.function.Function<String, Estado> buscarEstadoAP = (nombre) -> {
            for (Estado es : listaEstados) {
                if (es.getNombre().equals(nombre)) {
                    return es;
                }
            }
            System.err.println("ERROR: Estado no encontrado: " + nombre);
            return null;
        };

        List<TransicionAP> listaTransiciones = new ArrayList<TransicionAP>();
        System.out.println("=== Procesando Transiciones AP ===");
        System.out.println("Número de transiciones a procesar: " + (trs != null ? ((List)trs).size() : 0));
        
        if (trs != null) {
            for (Object o : (List)trs) {
                System.out.println("Procesando objeto: " + o.getClass().getSimpleName());
                if (o instanceof Map) {
                    Map<String, String> transMap = (Map<String, String>)o;
                    System.out.println("Mapa de transición: " + transMap);
                    
                    String nombreOrigen = transMap.get("origen");
                    String simboloEntrada = transMap.get("simboloEntrada");
                    String simboloExtrae = transMap.get("simboloExtrae");
                    String nombreDestino = transMap.get("destino");
                    String simboloInserta = transMap.get("simboloInserta");
                    
                    System.out.println("Origen: " + nombreOrigen + ", Entrada: " + simboloEntrada + 
                                     ", Extrae: " + simboloExtrae + ", Destino: ..." + nombreDestino + 
                                     ", Inserta: " + simboloInserta);
                    
                    Estado origen = buscarEstadoAP.apply(nombreOrigen);
                    Estado destino = buscarEstadoAP.apply(nombreDestino);
                    
                    if (origen != null && destino != null) {
                        TransicionAP transicion = new TransicionAP(origen, simboloEntrada, simboloExtrae, destino, simboloInserta);
                        listaTransiciones.add(transicion);
                        System.out.println("Transición AP agregada: " + transicion);
                    } else {
                        System.err.println("ERROR: No se pudo crear transición - Origen: " + origen + ", Destino: " + destino);
                    }
                }
            }
        }

        System.out.println("=== Transiciones AP Procesadas ===");
        if (listaTransiciones.isEmpty()) {
            System.out.println("  No se procesaron transiciones AP");
            System.out.println("  trs = " + trs);
        } else {
            for (TransicionAP t : listaTransiciones) {
                if (t.getOrigen() != null && t.getDestino() != null) {
                    System.out.println("  " + t);
                } else {
                    System.err.println("ERROR: Transición inválida - " + t);
                }
            }
        }

        Estado inicial = null;
        List<Estado> aceptacion = new ArrayList<Estado>();
        for (Estado e : listaEstados) {
            if (e.isInicial()) inicial = e;
            if (e.isAceptacion()) aceptacion.add(e);
        }

        AP nuevo = new AP(nombreAutomata, listaEstados, (List<String>)alf, (List<String>)alfp, inicial, aceptacion, listaTransiciones);
        GestorAutomatas.agregarAutomata(nuevo);
        System.out.println("[OK] AP agregado: " + nuevo.getNombre());
        System.out.println("Número de transiciones en AP: " + nuevo.getTransiciones().size());

        RESULT = nuevo;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("ap",5, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-41)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // afd ::= MENOR AFD NOMBRE IGUAL CADENA MAYOR ID IGUAL LLAVE_IZQ estados LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ alfabeto LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ estado_inicial LLAVE_DER PUNTO_COMA ID IGUAL LLAVE_IZQ estados_aceptacion LLAVE_DER PUNTO_COMA TRANSICIONES DOS_PUNTOS transiciones_afd MENOR_DIAGONAL AFD MAYOR 
            {
              Object RESULT =null;
		int nombreCadenaleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-31)).left;
		int nombreCadenaright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-31)).right;
		String nombreCadena = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-31)).value;
		int estleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).left;
		int estright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).right;
		List<String> est = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-26)).value;
		int alfleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).left;
		int alfright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).right;
		List<String> alf = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-20)).value;
		int eileft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).left;
		int eiright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).right;
		String ei = (String)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-14)).value;
		int eaccleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).left;
		int eaccright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).right;
		List<String> eacc = (List<String>)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-8)).value;
		int trsleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).left;
		int trsright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).right;
		List trs = (List)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-3)).value;
		 
        String nombreAutomata = (String)nombreCadena;

        List<Estado> listaEstados = new ArrayList<Estado>();
        for (String n : (List<String>)est) {
            Estado e = new Estado(n);
            if (n != null && n.equals(ei)) e.setInicial(true);
            if (eacc != null && ((List<String>)eacc).contains(n)) e.setAceptacion(true);
            listaEstados.add(e);
        }

        System.out.println("=== Estados AFD ===");
        for (Estado ee : listaEstados) {
            System.out.println("  " + ee);
        }

        System.out.println("=== Alfabeto AFD ===");
        if (alf != null) {
            for (String s : (List<String>)alf) System.out.println("  " + s);
        }

        // Método auxiliar para buscar estados por nombre
        java.util.function.Function<String, Estado> buscarEstado = (nombre) -> {
            for (Estado es : listaEstados) {
                if (es.getNombre().equals(nombre)) {
                    return es;
                }
            }
            System.err.println("ERROR: Estado no encontrado: " + nombre);
            return null;
        };

        // En la sección AFD, el procesamiento se simplifica:
        List<TransicionAFD> listaTransiciones = new ArrayList<TransicionAFD>();
        if (trs != null) {
            for (Object o : (List)trs) {
                if (o instanceof Map) {
                    Map<String, String> transMap = (Map<String, String>)o;
                    String nombreOrigen = transMap.get("origen");
                    String simbolo = transMap.get("simbolo");
                    String nombreDestino = transMap.get("destino");

                    Estado origen = buscarEstado.apply(nombreOrigen);
                    Estado destino = buscarEstado.apply(nombreDestino);

                    if (origen != null && destino != null) {
                        listaTransiciones.add(new TransicionAFD(origen, simbolo, destino));
                    }
                }
            }
        }
        System.out.println("=== Transiciones AFD ===");
        for (TransicionAFD t : listaTransiciones) {
            if (t.getOrigen() != null && t.getDestino() != null) {
                System.out.println("  " + t);
            } else {
                System.err.println("ERROR: Transición inválida - " + t);
            }
        }

        Estado inicial = null;
        List<Estado> aceptacion = new ArrayList<Estado>();
        for (Estado e : listaEstados) {
            if (e.isInicial()) inicial = e;
            if (e.isAceptacion()) aceptacion.add(e);
        }

        AFD nuevo = new AFD(nombreAutomata, listaEstados, (List<String>)alf, inicial, aceptacion, listaTransiciones);
        GestorAutomatas.agregarAutomata(nuevo);
        System.out.println("[OK] AFD agregado: " + nuevo.getNombre());

        RESULT = nuevo;
    
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("afd",4, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-35)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // automata ::= ap 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("automata",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // automata ::= afd 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("automata",3, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // elemento ::= comando 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("elemento",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // elemento ::= automata 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("elemento",2, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // contenido ::= contenido elemento 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("contenido",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // contenido ::= 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("contenido",1, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= contenido 
            {
              Object RESULT =null;

              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalizadorSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalizadorSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.elementAt(CUP$AnalizadorSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalizadorSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalizadorSintactico$parser.done_parsing();
          return CUP$AnalizadorSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

