
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Sep 11 19:01:58 CST 2025
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TRANSICIONES = 8;
  public static final int MENOR = 2;
  public static final int CADENA = 23;
  public static final int DESC = 10;
  public static final int OR = 20;
  public static final int IGUAL = 11;
  public static final int FLECHA = 19;
  public static final int AFD = 5;
  public static final int ID = 21;
  public static final int AP = 6;
  public static final int DOS_PUNTOS = 18;
  public static final int VER_AUTOMATAS = 9;
  public static final int PAREN_IZQ = 14;
  public static final int COMA = 16;
  public static final int PAREN_DER = 15;
  public static final int NOMBRE = 7;
  public static final int MAYOR = 3;
  public static final int EOF = 0;
  public static final int NUMERO = 22;
  public static final int error = 1;
  public static final int LLAVE_IZQ = 12;
  public static final int PUNTO_COMA = 17;
  public static final int LLAVE_DER = 13;
  public static final int MENOR_DIAGONAL = 4;
  public static final int STACKTOP = 25;
  public static final int LAMBDA = 24;

  public static final String[] terminalNames = {
    "EOF",              // 0
    "error",            // 1
    "MENOR",            // 2
    "MAYOR",            // 3
    "MENOR_DIAGONAL",   // 4
    "AFD",              // 5
    "AP",               // 6
    "NOMBRE",           // 7
    "TRANSICIONES",     // 8
    "VER_AUTOMATAS",    // 9
    "DESC",             // 10
    "IGUAL",            // 11
    "LLAVE_IZQ",        // 12
    "LLAVE_DER",        // 13
    "PAREN_IZQ",        // 14
    "PAREN_DER",        // 15
    "COMA",             // 16
    "PUNTO_COMA",       // 17
    "DOS_PUNTOS",       // 18
    "FLECHA",           // 19
    "OR",               // 20
    "ID",               // 21
    "NUMERO",           // 22
    "CADENA",           // 23
    "LAMBDA",           // 24
    "STACKTOP"          // 25
  };
}
